apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-hooks
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  {{- if .Values.apps.helm_hooks.appAnnotations }}
  annotations:
  {{ toYaml .Values.apps.helm_hooks.appAnnotations | nindent 2 }}
  {{- end }}
spec:
  destination:
    namespace: helm-hooks
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: helm-hooks
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}

