apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-guestbook
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  {{- if .Values.apps.kustomize_guestbook.appAnnotations }}
  annotations:
  {{ toYaml .Values.apps.kustomize_guestbook.appAnnotations | nindent 2 }}
  {{- end }}
spec:
  destination:
    namespace: kustomize-guestbook
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: kustomize-guestbook
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
