apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sync-waves
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  {{- if .Values.apps.sync_waves.appAnnotations }}
  annotations:
  {{ toYaml .Values.apps.sync_waves.appAnnotations | nindent 2 }}
  {{- end }}
spec:
  destination:
    namespace: sync-waves
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: sync-waves
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
